use online_voting_application;
drop table state;
drop table district;

CREATE TABLE state
(
    state_id   INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
    state_name VARCHAR(255) NOT NULL
);

INSERT INTO state (state_name)
VALUES ('Andaman and Nicobar Islands'),
       ('Andhra Pradesh'),
       ('Arunachal Pradesh'),
       ('Assam'),
       ('Bihar'),
       ('Chhattisgarh'),
       ('Chandigarh'),
       ('Daman and Diu'),
       ('Delhi'),
       ('Dadra and Nagar Haveli'),
       ('Goa'),
       ('Gujarat'),
       ('Himachal Pradesh'),
       ('Haryana'),
       ('Jammu and Kashmir'),
       ('Jharkhand'),
       ('Kerala'),
       ('Karnataka'),
       ('Lakshadweep'),
       ('Meghalaya'),
       ('Maharashtra'),
       ('Manipur'),
       ('Madhya Pradesh'),
       ('Mizoram'),
       ('Nagaland'),
       ('Odisha'),
       ('Punjab'),
       ('Puducherry'),
       ('Rajasthan'),
       ('Sikkim'),
       ('Tamil Nadu'),
       ('Telangana'),
       ('Tripura'),
       ('Uttar Pradesh'),
       ('Uttarakhand'),
       ('West Bengal');

select *
from state;

CREATE TABLE district
(
    district_id   INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
    district_name VARCHAR(255) NOT NULL,
    state_id      INT          NOT NULL,
    FOREIGN KEY (state_id) REFERENCES state (state_id)
);


drop table district;

INSERT INTO district (district_name, state_id)
VALUES ('North and Middle Andaman', 1),
       ('South Andaman', 1),
       ('Nicobar', 1);

INSERT INTO district (district_name, state_id)
VALUES ('Anantapur', 2),
       ('Chittoor', 2),
       ('East Godavari', 2),
       ('Guntur', 2),
       ('Krishna', 2),
       ('Kurnool', 2),
       ('Nellore', 2),
       ('Prakasam', 2),
       ('Srikakulam', 2),
       ('Visakhapatnam', 2),
       ('Vizianagaram', 2),
       ('West Godavari', 2),
       ('YSR Kadapa', 2);

INSERT INTO district (district_name, state_id)
VALUES ('Anjaw', 3),
       ('Changlang', 3),
       ('Dibang Valley', 3),
       ('East Kameng', 3),
       ('East Siang', 3),
       ('Kamle', 3),
       ('Kra Daadi', 3),
       ('Kurung Kumey', 3),
       ('Lepa Rada', 3),
       ('Lohit', 3),
       ('Longding', 3),
       ('Lower Dibang Valley', 3),
       ('Lower Subansiri', 3),
       ('Namsai', 3),
       ('Papum Pare', 3),
       ('Shi Yomi', 3),
       ('Siang', 3),
       ('Tawang', 3),
       ('Tirap', 3),
       ('Upper Siang', 3),
       ('Upper Subansiri', 3),
       ('West Kameng', 3),
       ('West Siang', 3);

INSERT INTO district (district_name, state_id)
VALUES ('Baksa', 4),
       ('Barpeta', 4),
       ('Biswanath', 4),
       ('Bongaigaon', 4),
       ('Cachar', 4),
       ('Charaideo', 4),
       ('Chirang', 4),
       ('Darrang', 4),
       ('Dhemaji', 4),
       ('Dhubri', 4),
       ('Dibrugarh', 4),
       ('Digboi', 4),
       ('Dima Hasao', 4),
       ('Goalpara', 4),
       ('Golaghat', 4),
       ('Hailakandi', 4),
       ('Hojai', 4),
       ('Jorhat', 4),
       ('Kamrup Metropolitan', 4),
       ('Kamrup Rural', 4),
       ('Karbi Anglong', 4),
       ('Karimganj', 4),
       ('Kokrajhar', 4),
       ('Lakhimpur', 4),
       ('Majuli', 4),
       ('Morigaon', 4),
       ('Nagaon', 4),
       ('Nalbari', 4),
       ('Sivasagar', 4),
       ('Sonitpur', 4),
       ('South Salmara-Mankachar', 4),
       ('Tinsukia', 4),
       ('Udalguri', 4),
       ('West Karbi Anglong', 4);

INSERT INTO district (district_name, state_id)
VALUES ('Araria', 5),
       ('Arwal', 5),
       ('Aurangabad', 5),
       ('Banka', 5),
       ('Begusarai', 5),
       ('Bhagalpur', 5),
       ('Bhojpur', 5),
       ('Buxar', 5),
       ('Darbhanga', 5),
       ('East Champaran', 5),
       ('Gaya', 5),
       ('Gopalganj', 5),
       ('Jamui', 5),
       ('Jehanabad', 5),
       ('Kaimur', 5);

INSERT INTO district (district_name, state_id)
VALUES ('Balod', 6),
       ('Baloda Bazar', 6),
       ('Bilaspur', 6),
       ('Dantewada', 6),
       ('Dhamtari', 6),
       ('Durg', 6),
       ('Gariaband', 6),
       ('Janjgir-Champa', 6),
       ('Jashpur', 6),
       ('Kanker', 6),
       ('Kawardha', 6),
       ('Kondagaon', 6),
       ('Korba', 6),
       ('Korea', 6),
       ('Mahasamund', 6),
       ('Mungeli', 6),
       ('Narayanpur', 6),
       ('Raipur', 6),
       ('Rajnandgaon', 6),
       ('Sukma', 6),
       ('Surajpur', 6),
       ('Surguja', 6);

INSERT INTO district (district_name, state_id)
VALUES ('Chandigarh', 7);

INSERT INTO district (district_name, state_id)
VALUES ('Daman', 8),
       ('Diu', 8);

INSERT INTO district (district_name, state_id)
VALUES ('Central Delhi', 9),
       ('East Delhi', 9),
       ('New Delhi', 9),
       ('North Delhi', 9),
       ('North East Delhi', 9),
       ('North West Delhi', 9),
       ('Shahdara', 9),
       ('South Delhi', 9),
       ('South East Delhi', 9),
       ('South West Delhi', 9),
       ('West Delhi', 9);

INSERT INTO district (district_name, state_id)
VALUES ('Dadra and Nagar Haveli', 10);

INSERT INTO district (district_name, state_id)
VALUES ('North Goa', 11),
       ('South Goa', 11);

INSERT INTO district (district_name, state_id)
VALUES ('Ahmedabad', 12),
       ('Amreli', 12),
       ('Anand', 12),
       ('Aravalli', 12),
       ('Banaskantha', 12),
       ('Bharuch', 12),
       ('Bhavnagar', 12),
       ('Botad', 12),
       ('Chhota Udaipur', 12),
       ('Dahod', 12),
       ('Dangs', 12),
       ('Devbhoomi Dwarka', 12),
       ('Gandhinagar', 12),
       ('Gir Somnath', 12),
       ('Jamnagar', 12),
       ('Junagadh', 12),
       ('Kachchh', 12),
       ('Kheda', 12),
       ('Mahisagar', 12),
       ('Mandi', 12),
       ('Mehsana', 12),
       ('Morbi', 12),
       ('Narmada', 12),
       ('Navsari', 12),
       ('Panchmahal', 12),
       ('Patan', 12),
       ('Porbandar', 12),
       ('Rajkot', 12),
       ('Sabarkantha', 12),
       ('Surat', 12),
       ('Surendranagar', 12),
       ('Tapi', 12),
       ('Vadodara', 12),
       ('Valsad', 12);

INSERT INTO district (district_name, state_id)
VALUES ('Bilaspur', 13),
       ('Chamba', 13),
       ('Hamirpur', 13),
       ('Kangra', 13),
       ('Kinnaur', 13),
       ('Kullu', 13),
       ('Lahaul and Spiti', 13),
       ('Mandi', 13),
       ('Shimla', 13),
       ('Sirmaur', 13),
       ('Solan', 13),
       ('Una', 13);

INSERT INTO district (district_name, state_id)
VALUES ('Ambala', 14),
       ('Bhiwani', 14),
       ('Charkhi Dadri', 14),
       ('Faridabad', 14),
       ('Fatehabad', 14),
       ('Gurgaon', 14),
       ('Hisar', 14),
       ('Jhajjar', 14),
       ('Jind', 14),
       ('Kaithal', 14),
       ('Karnal', 14),
       ('Kurukshetra', 14),
       ('Mahendragarh', 14),
       ('Mewat', 14),
       ('Palwal', 14),
       ('Panchkula', 14),
       ('Panipat', 14),
       ('Rewari', 14),
       ('Rohtak', 14),
       ('Sirsa', 14),
       ('Sonipat', 14),
       ('Yamunanagar', 14);

INSERT INTO district (district_name, state_id)
VALUES ('Anantnag', 15),
       ('Bandipora', 15),
       ('Baramulla', 15),
       ('Budgam', 15),
       ('Doda', 15),
       ('Ganderbal', 15),
       ('Jammu', 15),
       ('Kathua', 15),
       ('Kishtwar', 15),
       ('Kulgam', 15),
       ('Kupwara', 15),
       ('Poonch', 15),
       ('Pulwama', 15),
       ('Rajouri', 15),
       ('Ramban', 15),
       ('Reasi', 15),
       ('Samba', 15),
       ('Shopian', 15),
       ('Srinagar', 15),
       ('Udhampur', 15);

INSERT INTO district (district_name, state_id)
VALUES ('Bokaro', 16),
       ('Chatra', 16),
       ('Deoghar', 16),
       ('Dhanbad', 16),
       ('Dumka', 16),
       ('East Singhbhum', 16),
       ('Garhwa', 16),
       ('Giridih', 16),
       ('Godda', 16),
       ('Gumla', 16),
       ('Hazaribagh', 16),
       ('Jamtara', 16),
       ('Khunti', 16),
       ('Koderma', 16),
       ('Latehar', 16),
       ('Lohardaga', 16),
       ('Pakur', 16),
       ('Palamu', 16),
       ('Ramgarh', 16),
       ('Ranchi', 16),
       ('Sahebganj', 16),
       ('Seraikela Kharsawan', 16),
       ('Simdega', 16),
       ('West Singhbhum', 16);

INSERT INTO district (district_name, state_id)
VALUES ('Alappuzha', 17),
       ('Ernakulam', 17),
       ('Idukki', 17),
       ('Kannur', 17),
       ('Kasaragod', 17),
       ('Kollam', 17),
       ('Kottayam', 17),
       ('Kozhikode', 17),
       ('Malappuram', 17),
       ('Palakkad', 17),
       ('Pathanamthitta', 17),
       ('Thiruvananthapuram', 17),
       ('Thrissur', 17),
       ('Wayanad', 17);

INSERT INTO district (district_name, state_id)
VALUES ('Bagalkot', 18),
       ('Ballari', 18),
       ('Belagavi', 18),
       ('Bengaluru Rural', 18),
       ('Bengaluru Urban', 18),
       ('Bidar', 18),
       ('Chamarajanagara', 18),
       ('Chikkamagaluru', 18),
       ('Chikkaballapura', 18),
       ('Chitradurga', 18),
       ('Dakshina Kannada', 18),
       ('Davanagere', 18),
       ('Dharwad', 18),
       ('Gadag', 18),
       ('Haveri', 18),
       ('Hassan', 18),
       ('Haveri', 18),
       ('Kalaburagi', 18),
       ('Kodagu', 18),
       ('Kolar', 18),
       ('Koppal', 18),
       ('Mandya', 18),
       ('Mysuru', 18),
       ('Raichur', 18),
       ('Ramanagara', 18),
       ('Shivamogga', 18),
       ('Tumakuru', 18),
       ('Udupi', 18),
       ('Vijayapura', 18),
       ('Yadgir', 18);

INSERT INTO district (district_name, state_id)
VALUES ('Lakshadweep', 19);

INSERT INTO district (district_name, state_id)
VALUES ('East Garo Hills', 20),
       ('East Khasi Hills', 20),
       ('Jaintia Hills', 20),
       ('Ri Bhoi', 20),
       ('South Garo Hills', 20),
       ('South West Garo Hills', 20),
       ('West Garo Hills', 20),
       ('West Khasi Hills', 20);

INSERT INTO district (district_name, state_id)
VALUES ('Ahmednagar', 21),
       ('Akola', 21),
       ('Amravati', 21),
       ('Aurangabad', 21),
       ('Beed', 21),
       ('Bhandara', 21),
       ('Buldhana', 21),
       ('Chandrapur', 21),
       ('Dhule', 21),
       ('Gadchiroli', 21),
       ('Gondia', 21),
       ('Hingoli', 21),
       ('Jalgaon', 21),
       ('Jalna', 21),
       ('Kolhapur', 21),
       ('Latur', 21),
       ('Mumbai City', 21),
       ('Mumbai Suburban', 21),
       ('Nagpur', 21),
       ('Nanded', 21),
       ('Nashik', 21),
       ('Osmanabad', 21),
       ('Palghar', 21),
       ('Parbhani', 21),
       ('Pune', 21),
       ('Raigad', 21),
       ('Ratnagiri', 21),
       ('Sangli', 21),
       ('Satara', 21),
       ('Sindhudurg', 21),
       ('Solapur', 21),
       ('Thane', 21),
       ('Wardha', 21),
       ('Washim', 21),
       ('Yavatmal', 21);

INSERT INTO district (district_name, state_id)
VALUES ('Bishnupur', 22),
       ('Chandel', 22),
       ('Churachandpur', 22),
       ('Imphal East', 22),
       ('Imphal West', 22),
       ('Jiribam', 22),
       ('Kakching', 22),
       ('Kangpokpi', 22),
       ('Noney', 22),
       ('Senapati', 22),
       ('Tamenglong', 22),
       ('Thoubal', 22),
       ('Ukhrul', 22);

INSERT INTO district (district_name, state_id)
VALUES ('Agar Malwa', 23),
       ('Alirajpur', 23),
       ('Anuppur', 23),
       ('Ashoknagar', 23),
       ('Balaghat', 23),
       ('Barwani', 23),
       ('Betul', 23),
       ('Bhind', 23),
       ('Bhopal', 23),
       ('Burhanpur', 23),
       ('Chhatarpur', 23),
       ('Chhindwara', 23),
       ('Damoh', 23),
       ('Datia', 23),
       ('Dewas', 23),
       ('Dhar', 23),
       ('Dindori', 23),
       ('Guna', 23),
       ('Gwalior', 23),
       ('Harda', 23),
       ('Hoshangabad', 23),
       ('Indore', 23),
       ('Jabalpur', 23),
       ('Jhabua', 23),
       ('Katni', 23),
       ('Khandwa', 23),
       ('Khargone', 23),
       ('Mandla', 23),
       ('Mandsaur', 23),
       ('Morena', 23),
       ('Narmadapuram', 23),
       ('Neemuch', 23),
       ('Panna', 23),
       ('Raisen', 23),
       ('Rajgarh', 23),
       ('Ratlam', 23),
       ('Rewa', 23),
       ('Sagar', 23),
       ('Satna', 23),
       ('Sehore', 23),
       ('Seoni', 23),
       ('Shahdol', 23),
       ('Shajapur', 23),
       ('Sheopur', 23),
       ('Shivpuri', 23),
       ('Sidhi', 23),
       ('Singrauli', 23),
       ('Tikamgarh', 23),
       ('Ujjain', 23),
       ('Umaria', 23),
       ('Vidisha', 23),
       ('Umaria', 23);

INSERT INTO district (district_name, state_id)
VALUES ('Aizawl', 24),
       ('Champhai', 24),
       ('Kolasib', 24),
       ('Lawngtlai', 24),
       ('Lunglei', 24),
       ('Mamit', 24),
       ('Serchhip', 24),
       ('Siaha', 24);

INSERT INTO district (district_name, state_id)
VALUES ('Dimapur', 25),
       ('Kiphire', 25),
       ('Kohima', 25),
       ('Longleng', 25),
       ('Mokokchung', 25),
       ('Mon', 25),
       ('Peren', 25),
       ('Phek', 25),
       ('Tuensang', 25),
       ('Wokha', 25);

INSERT INTO district (district_name, state_id)
VALUES ('Angul', 26),
       ('Balangir', 26),
       ('Balasore', 26),
       ('Bargarh', 26),
       ('Bhadrak', 26),
       ('Boudh', 26),
       ('Cuttack', 26),
       ('Deogarh', 26),
       ('Dhenkanal', 26),
       ('Gajapati', 26),
       ('Ganjam', 26),
       ('Jagatsinghpur', 26),
       ('Jajpur', 26),
       ('Jharsuguda', 26),
       ('Kalahandi', 26),
       ('Kandhamal', 26),
       ('Kendrapara', 26),
       ('Keonjhar', 26),
       ('Khordha', 26),
       ('Koraput', 26),
       ('Malkangiri', 26),
       ('Mayurbhanj', 26),
       ('Nabarangpur', 26),
       ('Nayagarh', 26),
       ('Nuapada', 26),
       ('Puri', 26),
       ('Rayagada', 26),
       ('Sambalpur', 26),
       ('Sonepur', 26),
       ('Sundargarh', 26);

INSERT INTO district (district_name, state_id)
VALUES ('Amritsar', 27),
       ('Barnala', 27),
       ('Bathinda', 27),
       ('Ferozepur', 27),
       ('Fazilka', 27),
       ('Fatehgarh Sahib', 27),
       ('Gurdaspur', 27),
       ('Hoshiarpur', 27),
       ('Jalandhar', 27),
       ('Kapurthala', 27),
       ('Ludhiana', 27),
       ('Mansa', 27),
       ('Moga', 27),
       ('Muktsar Sahib', 27),
       ('Nawanshahr', 27),
       ('Pathankot', 27),
       ('Patiala', 27),
       ('Rupnagar', 27),
       ('Sangrur', 27),
       ('Shaheed Bhagat Singh Nagar', 27),
       ('Tarn Taran', 27);

INSERT INTO district (district_name, state_id)
VALUES ('Karaikal', 28),
       ('Mahe', 28),
       ('Puducherry', 28),
       ('Yanam', 28);

INSERT INTO district (district_name, state_id)
VALUES ('Ajmer', 29),
       ('Alwar', 29),
       ('Banswara', 29),
       ('Baran', 29),
       ('Bharatpur', 29),
       ('Bhilwara', 29),
       ('Bikaner', 29),
       ('Churu', 29),
       ('Dausa', 29),
       ('Dholpur', 29),
       ('Dungarpur', 29),
       ('Hanumangarh', 29),
       ('Jaipur', 29),
       ('Jaisalmer', 29),
       ('Jalore', 29),
       ('Jodhpur', 29),
       ('Karauli', 29),
       ('Kota', 29),
       ('Ladnun', 29),
       ('Lalsot', 29),
       ('Loharu', 29),
       ('Nagar', 29),
       ('Pali', 29),
       ('Pratapgarh', 29),
       ('Rajsamand', 29),
       ('Sawai Madhopur', 29),
       ('Sikar', 29),
       ('Sirohi', 29),
       ('Tonk', 29),
       ('Udaipur', 29);

INSERT INTO district (district_name, state_id)
VALUES ('East Sikkim', 30),
       ('North Sikkim', 30),
       ('South Sikkim', 30),
       ('West Sikkim', 30);

INSERT INTO district (district_name, state_id)
VALUES ('Ariyalur', 31),
       ('Chennai', 31),
       ('Coimbatore', 31),
       ('Cuddalore', 31),
       ('Dharmapuri', 31),
       ('Dindigul', 31),
       ('Erode', 31),
       ('Kanchipuram', 31),
       ('Kanyakumari', 31),
       ('Karur', 31),
       ('Krishnagiri', 31),
       ('Madurai', 31),
       ('Mayiladuthurai', 31),
       ('Nagapattinam', 31),
       ('Namakkal', 31),
       ('Nilgiris', 31),
       ('Perambalur', 31),
       ('Pudukkottai', 31),
       ('Ramanathapuram', 31),
       ('Salem', 31),
       ('Sivaganga', 31),
       ('Thanjavur', 31),
       ('Theni', 31),
       ('Thoothukudi', 31),
       ('Tiruchirappalli', 31),
       ('Tirunelveli', 31),
       ('Tiruppur', 31),
       ('Tiruvallur', 31),
       ('Vellore', 31),
       ('Viluppuram', 31),
       ('Virudhunagar', 31);

INSERT INTO district (district_name, state_id)
VALUES ('Adilabad', 32),
       ('Bhadradri Kothagudem', 32),
       ('Hyderabad', 32),
       ('Jagtial', 32),
       ('Jangaon', 32),
       ('Khammam', 32),
       ('Komaram Bheem Asifabad', 32),
       ('Mahabubabad', 32),
       ('Mahbubnagar', 32),
       ('Medak', 32),
       ('Nalgonda', 32),
       ('Nirmal', 32),
       ('Peddapalli', 32),
       ('Rajanna Sircilla', 32),
       ('Rangareddy', 32),
       ('Sangareddy', 32),
       ('Siddipet', 32),
       ('Vikarabad', 32),
       ('Warangal Rural', 32),
       ('Warangal Urban', 32);

INSERT INTO district (district_name, state_id)
VALUES ('Dhalai', 33),
       ('North Tripura', 33),
       ('South Tripura', 33),
       ('West Tripura', 33);

INSERT INTO district (district_name, state_id)
VALUES ('Agra', 34),
       ('Aligarh', 34),
       ('Ambedkar Nagar', 34),
       ('Amethi', 34),
       ('Auraiya', 34),
       ('Azamgarh', 34),
       ('Baghpat', 34),
       ('Bahraich', 34),
       ('Ballia', 34),
       ('Balrampur', 34),
       ('Banda', 34),
       ('Barabanki', 34),
       ('Bareilly', 34),
       ('Basti', 34),
       ('Bhadohi', 34),
       ('Bijnor', 34),
       ('Budaun', 34),
       ('Bulandshahr', 34),
       ('Chandauli', 34),
       ('Chitrakoot', 34),
       ('Deoria', 34),
       ('Etah', 34),
       ('Etawah', 34),
       ('Farrukhabad', 34),
       ('Fatehpur', 34),
       ('Firozabad', 34),
       ('Gautam Buddha Nagar', 34),
       ('Ghaziabad', 34),
       ('Ghazipur', 34),
       ('Gonda', 34),
       ('Gorakhpur', 34),
       ('Hamirpur', 34),
       ('Hardoi', 34),
       ('Hathras', 34),
       ('Jalaun', 34),
       ('Jaunpur', 34),
       ('Jhansi', 34),
       ('Kannauj', 34),
       ('Kanpur Dehat', 34),
       ('Kanpur Nagar', 34),
       ('Kaushambi', 34),
       ('Kheri', 34),
       ('Kushinagar', 34),
       ('Lakhimpur Kheri', 34),
       ('Lalitpur', 34),
       ('Lucknow', 34),
       ('Maharajganj', 34),
       ('Mahoba', 34),
       ('Mainpuri', 34),
       ('Mathura', 34),
       ('Mau', 34),
       ('Meerut', 34),
       ('Mirzapur', 34),
       ('Moradabad', 34),
       ('Muzaffarnagar', 34),
       ('Nainital', 34),
       ('Pilibhit', 34),
       ('Pratapgarh', 34),
       ('Prayagraj', 34),
       ('Raebareli', 34),
       ('Rampur', 34),
       ('Saharanpur', 34),
       ('Sambhal', 34),
       ('Sant Kabir Nagar', 34),
       ('Sant Ravidas Nagar (Bhadohi)', 34),
       ('Siddharthnagar', 34),
       ('Sitapur', 34),
       ('Sonbhadra', 34),
       ('Sultanpur', 34),
       ('Unnao', 34),
       ('Varanasi', 34);

INSERT INTO district (district_name, state_id)
VALUES ('Almora', 35),
       ('Bageshwar', 35),
       ('Chamoli', 35),
       ('Champawat', 35),
       ('Dehradun', 35),
       ('Haridwar', 35),
       ('Nainital', 35),
       ('Pauri Garhwal', 35),
       ('Pithoragarh', 35),
       ('Rudraprayag', 35),
       ('Tehri Garhwal', 35),
       ('Udham Singh Nagar', 35),
       ('Uttarkashi', 35);

INSERT INTO district (district_name, state_id)
VALUES ('Bankura', 36),
       ('Bardhaman', 36),
       ('Birbhum', 36),
       ('Cooch Behar', 36),
       ('Darjeeling', 36),
       ('Hooghly', 36),
       ('Howrah', 36),
       ('Jalpaiguri', 36),
       ('Jhargram', 36),
       ('Kalimpong', 36),
       ('Kolkata', 36),
       ('Malda', 36),
       ('Medinipur', 36),
       ('Murshidabad', 36),
       ('Nadia', 36),
       ('North 24 Parganas', 36),
       ('Purba Bardhaman', 36),
       ('Purulia', 36),
       ('South 24 Parganas', 36),
       ('West Midnapore', 36);

alter table state
modify column state_id varchar(5);

alter table district
modify column district_id varchar(5);

alter table district
modify column state_id varchar(5);

select *
from district;

select *
from state;

select * from state inner join district on state.state_id = district.state_id where state_name='Bihar';